# Generated by Django 4.0.4 on 2022-05-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StatsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_id', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('is_commerce', models.BooleanField(blank=True, null=True)),
                ('hashtag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to='tiktokscraper.hashtag')),
            ],
        ),
    ]
