# Generated by Django 4.0.4 on 2022-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokscraper', '0002_hashtag_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
