# Generated by Django 4.0.4 on 2022-05-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokscraper', '0003_hashtag_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='is_valid',
            new_name='is_valid_hashtag',
        ),
    ]
